name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2205
          script: |
                   cd ~/ameya-site
                   git pull origin main
                   npm install
                   npm run build
                   # Using -rf to ensure the build directory is overwritten without prompts
                   sudo cp -rf build/* /var/www/ameyabhat.me/ameya-site/build/
                   sudo systemctl reload nginx
                   # Restart the backend to apply Node.js changes
                   pm2 restart backend
