name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
                    cd ~/ameya-site
                    git pull origin main
                    npm install
                    npm run build

                    # 1. Update Frontend Files (No sudo needed for cp anymore!)
                    cp -rf build/* /var/www/ameyabhat.me/ameya-site/build/
                    sudo /bin/systemctl reload nginx

                    # 2. Update and Restart Backend
                    cd backend
                    npm install
        
                    # 3. USE npx TO BYPASS THE PM2 PATH ISSUE
                    npx pm2 restart ameya-api || npx pm2 start server.js --name "ameya-api"
                    npx pm2 save
